import { StyleSheet } from "react-native";

export const auth = StyleSheet.create({
  innerContainer: {
    paddingHorizontal: 30,
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#00000a",
  },
  logo: {
    fontSize: 42,
    fontWeight: "900",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: 4,
    fontStyle: "italic",
    textShadowColor: "rgba(255, 255, 255, 0.75)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 30,
    transform: [{ scaleX: 1.35 }],
  },
  welcomeText: {
    fontSize: 16,
    color: "#b3b3b3",
    textAlign: "center",
    marginBottom: 40,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2e2e2e",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#808080",
    height: 55,
    paddingHorizontal: 15,
  },
  input: {
    flex: 1,
    color: "#ffffff",
    fontSize: 16,
  },
  loginButton: {
    backgroundColor: "#2196F3",
    height: 55,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 25,
    elevation: 4,
  },
  loginText: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  forgotButton: {
    marginTop: 2,
    alignItems: "flex-end",
  },
  registerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
  },
  registerText: {
    color: "#b3b3b3",
    fontSize: 14,
  },
  linkText: {
    color: "#2196F3",
    fontWeight: "600",
  },
});

export const main = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#00000a",
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: 4,
    textShadowColor: "rgba(255, 255, 255, 0.75)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
    marginBottom: 20,
  },
  statsContainer: {
    gap: 10,
  },
  card: {
    borderRadius: 15,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    width: 130,
  },
  cardTitle: {
    color: "#b3b3b3",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  statsValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
    marginTop: 4,
  },
  grid: {
    flexDirection: "row",
  },
  levelContainer: {
    backgroundColor: "#2196f315",
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#2196f380",
  },
  progressBarBg: {
    height: 8,
    backgroundColor: "#333",
    borderRadius: 4,
    marginTop: 10,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#2196F3",
    width: "65%",
  },
  workoutCard: {
    backgroundColor: "#2196f315",
    borderRadius: 20,
    padding: 25,
    borderWidth: 1,
    borderColor: "#2196f380",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
});
