import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const auth = StyleSheet.create({
  innerContainer: {
    paddingHorizontal: 30,
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#00000a",
  },
  logo: {
    fontSize: 42,
    fontWeight: "900",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: 4,
    fontStyle: "italic",
    textShadowColor: "rgba(255, 255, 255, 0.75)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 30,
    transform: [{ scaleX: 1.35 }],
  },
  welcomeText: {
    fontSize: 16,
    color: "#b3b3b3",
    textAlign: "center",
    marginBottom: 40,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2e2e2e",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#808080",
    height: 55,
    paddingHorizontal: 15,
  },
  input: {
    flex: 1,
    color: "#ffffff",
    fontSize: 16,
  },
  filledBtn: {
    backgroundColor: "#2196F3",
    height: 55,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 25,
    elevation: 4,
  },
  filledBtnText: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  forgotButton: {
    marginTop: 2,
    alignItems: "flex-end",
  },
  registerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
  },
  registerText: {
    color: "#b3b3b3",
    fontSize: 14,
  },
  linkText: {
    color: "#2196F3",
    fontWeight: "600",
  },
});

export const main = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#00000a",
    paddingTop: 30,
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: 4,
    textShadowColor: "rgba(255, 255, 255, 0.75)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
    marginBottom: 20,
  },
  statsContainer: {
    gap: 10,
  },
  card: {
    borderRadius: 15,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    width: 130,
  },
  cardTitle: {
    color: "#b3b3b3",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  statsValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
    marginTop: 4,
  },
  grid: {
    flexDirection: "row",
  },
  levelContainer: {
    backgroundColor: "#2196f315",
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#2196f380",
  },
  progressBarBg: {
    height: 8,
    backgroundColor: "#333",
    borderRadius: 4,
    marginTop: 10,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#2196F3",
    width: "65%",
  },
  workoutCard: {
    backgroundColor: "#2196f315",
    borderRadius: 20,
    padding: 25,
    borderWidth: 1,
    borderColor: "#2196f380",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
});

export const logger = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  centerWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: 15,
    textTransform: "uppercase",
  },
  inputGroup: {
    backgroundColor: "#111",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: 10,
  },
  largeValue: {
    color: "#fff",
    fontSize: 72,
    fontWeight: "900",
    marginTop: 10,
  },
  unitText: {
    fontSize: 24,
    color: "rgba(255,255,255,0.5)",
  },
  quickAddGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 40,
    gap: 10,
  },
  quickAddBtn: {
    flex: 1,
    backgroundColor: "#0a0a1a",
    paddingVertical: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#333",
    alignItems: "center",
  },
  macroContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#111",
    padding: 20,
    borderRadius: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#222",
  },
  macroItem: {
    alignItems: "center",
  },
  macroLabel: {
    color: "#888",
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 4,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  photoSlot: {
    width: "48%",
    aspectRatio: 1,
    backgroundColor: "#111",
    borderRadius: 15,
    marginBottom: 15,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#333",
  },
  exerciseCard: {
    backgroundColor: "#111",
    padding: 18,
    borderRadius: 15,
    marginBottom: 15,
    borderLeftWidth: 4,
  },
  setInput: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#222",
  },
  submitBtn: {
    height: 60,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: "auto",
    marginBottom: 20,
  },
  submitBtnText: {
    color: "#000",
    fontWeight: "900",
    fontSize: 16,
    letterSpacing: 1,
  },
});

export const exercise = StyleSheet.create({
  exerciseCard: {
    backgroundColor: `${colors.blue}15`,
    borderRadius: 16,
    padding: 15,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: `${colors.blue}80`,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  exerciseTitle: {
    color: colors.blue,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 2,
  },
  exerciseInput: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 10,
  },
  setRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 6,
    gap: 8,
  },
  interactiveRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerText: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
  },
  setNumber: {
    color: "#fff",
    width: 30,
    textAlign: "center",
    fontWeight: "bold",
  },
  input: {
    flex: 1,
    backgroundColor: `${colors.black}50`,
    color: "#fff",
    textAlign: "center",
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: `${colors.blue}80`,
  },
  prevContainer: {
    flex: 1,
    alignItems: "center",
  },
  prevText: {
    color: colors.textDark,
    fontWeight: "600",
  },
  checkBtn: {
    width: 30,
    alignItems: "center",
  },
  addSetBtn: {
    marginTop: 15,
    paddingVertical: 5,
  },
  addSetText: {
    color: colors.blue,
    fontWeight: "bold",
    fontSize: 12,
  },
  fixedHeader: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 10,
  },
  scrollContent: {
    paddingTop: 20,
    paddingBottom: 120,
  },
  addExerciseBtn: {
    borderWidth: 1,
    borderColor: colors.blue,
    borderStyle: "dashed",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "rgba(33, 150, 243, 0.05)",
    marginBottom: 40,
  },
  addExerciseText: {
    color: colors.blue,
    fontWeight: "900",
    letterSpacing: 1,
  },
  fixedFooter: {
    position: "absolute",
    backgroundColor: colors.background,
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    paddingBottom: 0,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
  },
});
